Repository FRONTENDBOOTCAMP-14th/ui-project-team-10, pull requests merged in 2025-05, with the labels that each got.

#17 Feature/album/gyeongtae
  index.html
  package-lock.json
  src/assets/album-example.png
  src/assets/play.png
  src/components/album.html
  src/components/main.css
  src/components/main.html
  src/main.js
  src/scripts/album.js
  src/styles/album.css
Labels: 개선, 스타일, 경태

#25 Features/sidebar component
  public/icons/globe.svg
  src/components/sidebar.html
  src/styles/sidebar.css
Labels: 기능, 정일

#47 Feature/album card/gyeongtae
  public/icons/play.png
  public/image/default-album-cover.png
  src/components/album-card.html
  src/components/album.html
  src/components/artist.html
  src/components/main.html
  src/scripts/album.js
  src/scripts/artist.js
  src/scripts/main.js
  src/styles/album.css
  src/styles/artist.css
  src/styles/header.css
  src/styles/main.css
Labels: 개선, 기능, 경태

#51 Feature/footer html/woohyeun
  src/components/footer.html
  src/components/main.html
  src/styles/footer.css
  src/styles/main.css
Labels: 문서화, 기능, 우현
